version: 1.0.{build}

image: Visual Studio 2022

configuration : Release

before_build:
- cmd: nuget restore Irony.sln

build:
  project: Irony.sln
  parallel: true
  verbosity: minimal

artifacts:
- path: Irony/bin/Release/netstandard2.0/Irony.dll
- path: Irony/bin/Release/netstandard2.0/Irony.pdb
- path: packages/*.nupkg
